### ISSUE TITLE
Documentation Improvement: Correct Parameter and Return Type Descriptions for pipeline Function

### ISSUE THREAD

**Issue by sacha-renault** [natanfeitosa/pyfunctools#11]
### Documentation Improvement

Hello,
I noticed minor issues in the doc that could be improved for better clarity.

**Current Documentation:**

```
pyfunctools.pipeline.pipeline(*funcs)
Define a pipeline

Parameters
*funcs (list[callable]) – a list of callables to be called later
Returns
last pipe return
```
Issues Identified:

The parameter *funcs should be typed as callable and not list[callable].
The return type description "last pipe return" is unclear. The function actually returns a callable.

### Suggested Correction:

```
pyfunctools.pipeline.pipeline(*funcs)
Define a pipeline

Parameters
*funcs (callable) – a variable number of callables to be called sequentially later.

Returns
callable – a callable that, when invoked, executes the provided callables in sequence, passing the output of each as the input to the next, and returns the result of the last callable.
```

**Comment by natanfeitosa** [comment]
Thank you for the suggestion to improve the documentation! I really appreciate your contribution.

If you prefer, feel free to make the change directly by submitting a pull request. The documentation is generated from Python docstrings, so any adjustments to the docstrings will be automatically reflected in the next build.

If you have any questions, I'm here to help!
